language: ruby

install: echo "party time!!"

script: echo "like it's cat meow 99" && true

before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

deploy:
  - provider: s3
    access_key_id: AKIAIJGOFHHQTTDESNGQ
    secret_access_key: &1
      secure: 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
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: rajkumarcheekati/cat-party
    bucket: traviscicodedeploy
  - provider: codedeploy
    access_key_id: AKIAIJGOFHHQTTDESNGQ
    secret_access_key: *1
    region: ap-south-1
    bucket: traviscicodedeploy
    key: latest.zip
    bundle_type: zip
    application: travisCI
    deployment_group: testing
    on: *2
